# Generated by Django 4.1.2 on 2022-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="secret_key",
            field=models.CharField(default="305282", editable=False, max_length=6),
        ),
    ]
