# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="conta",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
