# Generated by Django 4.1.2 on 2022-11-04 12:03

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="cpf",
            field=cpf_field.models.CPFField(
                max_length=14, unique=True, verbose_name="cpf"
            ),
        ),
    ]
