# Generated by Django 4.1.2 on 2022-11-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
