# Generated by Django 4.1.2 on 2022-11-01 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_conta_cpf_alter_conta_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="conta",
            name="pontos_de_fidelidade",
            field=models.IntegerField(default=0),
        ),
    ]
