# Generated by Django 4.1.2 on 2022-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_conta_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
