# Generated by Django 4.1.2 on 2022-11-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_conta_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="secret_key",
            field=models.CharField(editable=False, max_length=6, null=True),
        ),
    ]
