# Generated by Django 4.1.2 on 2022-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_alter_conta_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
