# Generated by Django 4.1.2 on 2022-11-07 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0004_alter_conta_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="secret_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
