# Generated by Django 4.1.2 on 2022-11-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endereco",
            old_name="conta_id",
            new_name="conta",
        ),
    ]
