# Generated by Django 4.1.2 on 2022-11-02 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0002_rename_conta_id_endereco_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
