# Generated by Django 4.1.2 on 2022-11-02 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enderecos", "0004_alter_endereco_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="conta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endereco",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
